@echo off
REM Copy the addon from this repo into the WoW AddOns folder.
REM
REM The installed copy is the one the game runs, so it is the tempting one to
REM edit - and a plain copy in this direction would silently destroy those
REM edits. So: if the installed file differs AND is newer than the repo's,
REM this refuses to touch it and tells you, rather than overwriting work that
REM was never committed. That is the whole point of the exercise.
REM
REM Which files? Whatever is in the repo's addon folder, enumerated - NOT a
REM list written down here. The list was WowCraftExport.toc, main.lua and
REM prices.lua, so trade.lua, undercut.lua and inventory.lua were never synced
REM at all; they only ever reached the game inside a release zip. That stayed
REM invisible until the .toc gained a file the game did not have, and the
REM client refused to load an addon whose .toc pointed at nothing:
REM
REM     Error loading Interface/AddOns/WowCraftExport/craft.lua
REM
REM A hand-written list of files is a thing that goes stale the next time
REM somebody adds a file, and it fails in a way that looks like broken Lua.
REM
REM PriceData.lua is deliberately excluded. It is generated by `scan` straight
REM into the game folder and never committed, so installing would overwrite
REM fresh prices with nothing, and `back` would drag a 600 KB generated file
REM into the repo.
REM
REM Usage:  sync-addon.cmd          install repo -> game
REM         sync-addon.cmd back     bring game edits back into the repo

setlocal enabledelayedexpansion

set "SRC=%~dp0addon\WowCraftExport"
set "DST=D:\Games\World of Warcraft\_retail_\Interface\AddOns\WowCraftExport"

if not exist "%DST%" (
    echo Addon folder not found: "%DST%"
    echo Edit DST in this script if WoW lives somewhere else.
    exit /b 1
)

set "MODE=install"
if /i "%~1"=="back" set "MODE=back"

set CHANGED=0
set BLOCKED=0

for %%F in ("%SRC%\*.toc" "%SRC%\*.lua" "%SRC%\*.cmd") do (
    set "A=%%~fF"
    set "B=%DST%\%%~nxF"
    if /i "%%~nxF"=="PriceData.lua" (
        echo skipped ^(generated^): %%~nxF
    ) else (
        fc /b "!A!" "!B!" >nul 2>&1
        if errorlevel 1 (
            if "%MODE%"=="back" (
                REM Nothing to pull back from a file the game does not have -
                REM and copying a missing file over the repo's would be a
                REM quiet way to lose one.
                if exist "!B!" (
                    copy /y "!B!" "!A!" >nul && echo pulled back      : %%~nxF
                    set /a CHANGED+=1
                ) else (
                    echo not installed yet : %%~nxF
                )
            ) else (
                REM Which side is newer? %%~tF style comparison is awkward in
                REM batch, so ask PowerShell for a straight answer.
                for /f %%N in ('powershell -NoProfile -Command ^
                    "if ((Get-Item '!B!' -ErrorAction SilentlyContinue).LastWriteTime -gt (Get-Item '!A!').LastWriteTime) {'game'} else {'repo'}"') do set "NEWER=%%N"
                if "!NEWER!"=="game" (
                    echo REFUSED           : %%~nxF
                    echo     the installed copy differs and is NEWER than the repo's.
                    echo     Run "sync-addon.cmd back" to keep those edits, or delete
                    echo     the installed file if you meant to discard them.
                    set /a BLOCKED+=1
                ) else (
                    copy /y "!A!" "!B!" >nul && echo installed         : %%~nxF
                    set /a CHANGED+=1
                )
            )
        ) else (
            echo already in sync   : %%~nxF
        )
    )
)

echo.
if "%MODE%"=="back" (
    echo %CHANGED% file^(s^) pulled back into the repo. Commit them.
) else (
    echo %CHANGED% file^(s^) installed, %BLOCKED% refused.
)
if not "%BLOCKED%"=="0" exit /b 2
exit /b 0
